build:
  version: 1.0

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Rishi - Product Owner"
    email: "https://github.com/prakhar10104701/prakhar10104701-config"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
